#
# ==============
# playsound.sk
# ==============
# playsound.sk is part of the MINIGAMES.SK library.
# ==============

#
# > Function - playsound
# > Plays the sound. Is being used in a function since Skript parses
# > the vanilla Skript play sound very slowly.
function playsound(sound:text,volume:number,pitch:number,location:location,player:player):
  play sound {_sound} with volume {_volume} with pitch {_pitch} at {_location} for {_player}
